language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.00 PACKAGE=scheme_of_ocaml TESTS=true INSTALL=false
  - OCAML_VERSION=4.01 PACKAGE=scheme_of_ocaml TESTS=true INSTALL=false
  - OCAML_VERSION=4.02 PACKAGE=scheme_of_ocaml TESTS=true INSTALL=false
  - OCAML_VERSION=4.03 PACKAGE=scheme_of_ocaml TESTS=true INSTALL=false
  - OCAML_VERSION=4.04 PACKAGE=scheme_of_ocaml TESTS=true INSTALL=false
os:
  - linux
  - osx
