#!/usr/bin/env bash

ocamlbuild \
    -use-ocamlfind \
    -pkg core \
    -pkg ppx_deriving.show \
    -pkg ppx_deriving.eq \
    -pkg ppx_sexp_conv \
    -pkg ppx_jane \
    -tag thread \
    -tag debug \
    -tag bin_annot \
    -tag short_paths \
    -cflags "-w A-4-33-40-41-42-43-34-44" \
    -cflags -strict-sequence \
    $@
